# Generated by Django 3.2.3 on 2021-05-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='records',
        ),
        migrations.AlterModelTable(
            name='status',
            table='statuses',
        ),
    ]
