# Generated by Django 3.2.3 on 2021-05-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_records', '0002_auto_20210526_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
